final tweeks polishing:
 - added release repository creation config
 - added badges automatic generation workflow
 - added heading general summary section
 - replaced install one-liner for script

 - normalized workflow steps summary messages
 - normalized artifacts to markdown files

 - fixed some actions "not found" bug (parsing empty line as one hit)

diff --git a/.github/workflows/gwy-aws-release.yml b/.github/workflows/gwy-aws-release.yml
--- a/.github/workflows/gwy-aws-release.yml
+++ b/.github/workflows/gwy-aws-release.yml
@@ -1,4 +1,4 @@
-name: 'GWY/Release: AWS'
+name: 'GWY/Release: AWS/ECR'
 
 on:
   workflow_dispatch:
@@ -65,6 +65,8 @@ on:
         type: string
         default: '5m'
 
+run-name: "[${{ github.workflow }}] @${{ github.actor }}"
+
 jobs:
   gwy-release:
     runs-on: ubuntu-latest
@@ -83,9 +85,27 @@ jobs:
           # process target workflow branch 
           
           if [ "${{ inputs.branch }}" = "<CURRENT>" ]; then
-            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
+            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
           else
             echo "BRANCH=${{ inputs.branch }}" >> $GITHUB_ENV
+          fi
+
+      - name: GWY Bootstrapping Validations
+        run: |
+          # TODO: Add aws token validation
+          if [ -z "${{ secrets.GWY_TOKEN_AWS }}" ]; then
+            echo "::error title=Mandatory AWS token not configured::mandatory secret 'GWY_TOKEN_AWS' seems to be empty, kindly check GWY configuration documentation"
+            exit 1
+          fi
+          
+          if [ -z "${{ secrets.GWY_TOKEN_REPO }}" ]; then
+            echo "::error title=Mandatory repository token not configured::mandatory secret 'GWY_TOKEN_REPO' seems to be empty, kindly check GWY configuration documentation"
+            exit 1
+          fi
+          
+          if ! git ls-remote --exit-code https://x-access-token:${{ secrets.GWY_TOKEN_REPO }}@github.com/${{ github.repository }} "refs/heads/$BRANCH" "refs/tags/$BRANCH" > /dev/null; then
+            echo "::error title=Could not find workflow target branch::could not find branch or tag with name '$BRANCH', kindly provide a valid branch name."
+            exit 1
           fi
 
       - name: Checkout Code
@@ -123,6 +143,11 @@ jobs:
             GWY_RELEASE_TOKEN="${{ secrets.GWY_TOKEN_AWS }}"
           fi
 
+          if [ -z "$GWY_RELEASE_TOKEN" ]; then
+            echo "::error title=::"
+            exit 1
+          fi
+          
           # Export to env for action
           echo "GWY_RELEASE_TAG=$GWY_RELEASE_TAG" >> $GITHUB_ENV
           echo "GWY_RELEASE_TOKEN=$GWY_RELEASE_TOKEN" >> $GITHUB_ENV
diff --git a/.github/workflows/gwy-coverage.yml b/.github/workflows/gwy-coverage.yml
--- a/.github/workflows/gwy-coverage.yml
+++ b/.github/workflows/gwy-coverage.yml
@@ -24,9 +24,17 @@ on:
         type: string
         default: '60'
 
+      summary-threshold:
+        description: 'Show functions with less than? (%)'
+        required: false
+        type: string
+        default: '50'
+
+run-name: "[${{ github.workflow }}] @${{ github.actor }}"
+
 jobs:
   gwy-coverage:
-    name: tests coverage
+    name: tests and coverage
     runs-on: ubuntu-latest
     steps:
       - name: Set Branch
@@ -42,9 +50,21 @@ jobs:
 
           # process target workflow branch 
           if [ "${{ inputs.branch }}" = "<CURRENT>" ]; then
-            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
+            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
           else
             echo "BRANCH=${{ inputs.branch }}" >> $GITHUB_ENV
+          fi
+
+      - name: GWY Bootstrapping Validations
+        run: |
+          if [ -z "${{ secrets.GWY_TOKEN_REPO }}" ]; then
+            echo "::error title=Mandatory repository token not configured::mandatory secret 'GWY_TOKEN_REPO' seems to be empty, kindly check GWY configuration documentation"
+            exit 1
+          fi
+          
+          if ! git ls-remote --exit-code https://x-access-token:${{ secrets.GWY_TOKEN_REPO }}@github.com/${{ github.repository }} "refs/heads/$BRANCH" "refs/tags/$BRANCH" > /dev/null; then
+            echo "::error title=Could not find workflow target branch::could not find branch or tag with name '$BRANCH', kindly provide a valid branch name."
+            exit 1
           fi
 
       - name: Checkout Code
@@ -66,6 +86,7 @@ jobs:
         with:
           token: ${{ secrets.GWY_REPO_TOKEN }}
           threshold: ${{ inputs.coverage }}
+          summary-threshold: ${{ inputs.summary-threshold }}
 
       - name: Workflow Result
         shell: bash
diff --git a/.github/workflows/gwy-secrets.yml b/.github/workflows/gwy-secrets.yml
--- a/.github/workflows/gwy-secrets.yml
+++ b/.github/workflows/gwy-secrets.yml
@@ -18,9 +18,11 @@ on:
         type: string
         default: '5m'
 
+run-name: "[${{ github.workflow }}] @${{ github.actor }}"
+
 jobs:
   gwy-secrets:
-    name: code secrets (gitleaks)
+    name: code secrets scan
     runs-on: ubuntu-latest
     steps:
       - name: Set Branch
@@ -36,9 +38,21 @@ jobs:
 
           # process target workflow branch 
           if [ "${{ inputs.branch }}" = "<CURRENT>" ]; then
-            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
+            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
           else
             echo "BRANCH=${{ inputs.branch }}" >> $GITHUB_ENV
+          fi
+
+      - name: GWY Bootstrapping Validations
+        run: |
+          if [ -z "${{ secrets.GWY_TOKEN_REPO }}" ]; then
+            echo "::error title=Mandatory repository token not configured::mandatory secret 'GWY_TOKEN_REPO' seems to be empty, kindly check GWY configuration documentation"
+            exit 1
+          fi
+          
+          if ! git ls-remote --exit-code https://x-access-token:${{ secrets.GWY_TOKEN_REPO }}@github.com/${{ github.repository }} "refs/heads/$BRANCH" "refs/tags/$BRANCH" > /dev/null; then
+            echo "::error title=Could not find workflow target branch::could not find branch or tag with name '$BRANCH', kindly provide a valid branch name."
+            exit 1
           fi
 
       - name: Checkout Code
